language: php

php:
  - 7.2

before_install:
  - cp .env.example .env
  - sudo apt-get install -y nodejs

install:
  - composer install
  - npm install

script:
  - ./vendor/bin/phpunit --list-tests
  - ./vendor/bin/phpunit
  - npm run test-js
